version: "3.9"

services:
  # # Use for development only ---- 
  # redis:
  #   image: redis:7-alpine
  #   volumes:
  #     - redis:/data      
  #   ports:
  #     - '6379:6379'

  # postgres:
  #   image: postgres:17-alpine
  #   restart: always
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   env_file:
  #     - .env_docker
  #   ports:
  #     - "5432:5432"
  # # ----------------------------


  rust:
    build: ./backend/rust-service
    env_file:
      - .env_docker_backend
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./media:/app/media

  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile.nextjs
    env_file:
      - .env_docker_frontend
    ports:
      - "5175:5175"

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - nextjs
      - rust
    volumes:
      - ./media:/etc/nginx/media